pipeline {

  environment {
    registry = "registry.hub.docker.com/mohan1997/mohan-nagandlla"
    registryCredential = 'DockerHub'
    dockerImage = ""
  }

  agent any

  stages {

    stage('Cloning Source') {
      steps {
        git 'https://github.com/mohan-nagandlla/jenkins.git'
      }
    }

    stage('Build image') {
      steps{
        script {
          docker.withRegistry( 'https://registry.hub.docker.com', registryCredential ) {
            dockerImage = docker.build("$registry:$BUILD_NUMBER","--file=./agent_with_docker/Dockerfile .").push()
          }
        }
      }
    }
      


  }

}
