pipeline {

  environment {
    registry = "registry.hub.docker.com/mohan1997/mohan-nagandlla"
    registryCredential = 'DockerHub'
    dockerImage = ""
  }

  agent {
    dockerfile {
        dir './agent_with_docker'
        args '-v /tmp:/tmp'
               }
        }

  stages {

    stage('Cloning Source') {
      steps {
        git 'https://github.com/mohan-nagandlla/jenkins.git'
      }
    }
    stage('Build image') {
      steps{
        script {
          docker.withRegistry( "" , registryCredential ) {
            dockerImage = docker.build("$registry + ':$BUILD_NUMBER'","-f ./agent_with_docker/Dockerfile .")
            }
        }
      }
    }

    stage('Push Image') {
      steps{
        script {
          docker.withRegistry( "" , registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }

  }

}
