pipeline {

  environment {
    registry = "registry.hub.docker.com/mohan1997/mohan-nagandlla"
    registryCredential = 'DockerHub'
    dockerImage = ""
  }

  agent {
    dockerfile {
        dir './agent_with_docker/'
               }
        }

  stages {


    stage('Build image') {
      steps{
        script {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }

    stage('Push Image') {
      steps{
        script {
          docker.withRegistry( "" , registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }

  }

}
